import { Activity, ArrowRight, BarChart3, Check, ClipboardCheck, HeartPulse, ScanLine, ShieldCheck, Stethoscope, UsersRound } from 'lucide-react';
import { Link } from 'wouter';
import { BrandMark } from '@/components/app-shell';

const credibility = [
  { icon: Stethoscope, title: 'Clinician-led', text: 'Plans begin with professional guidance and stay grounded in the care relationship.' },
  { icon: ShieldCheck, title: 'Privacy-minded', text: 'Your movement data is treated as part of your care, with clarity and respect.' },
  { icon: HeartPulse, title: 'Human-first', text: 'Small, supportive prompts help rehabilitation fit into real life.' },
];

const features = [
  { icon: ScanLine, number: '01', title: 'AI Pose Analysis', text: 'Gentle visual feedback helps you notice alignment, range, and rhythm as you move.' },
  { icon: ClipboardCheck, number: '02', title: 'Personalized Rehabilitation Plans', text: 'Your physiotherapist sets the right exercise, dose, and movement target for you.' },
  { icon: BarChart3, number: '03', title: 'Progress Tracking', text: 'See your consistency and session signals build into a clearer picture over time.' },
];

const steps = [
  { number: '01', title: 'Doctor creates prescription', text: 'Your physiotherapist shapes a focused plan around your needs.' },
  { number: '02', title: 'Patient joins with doctor access code', text: 'Connect to the right clinician and bring your plan home.' },
  { number: '03', title: 'AI-guided movement session', text: 'Move at your pace with clear cues and supportive visual feedback.' },
  { number: '04', title: 'Therapist reviews results', text: 'Your clinician sees the signals that help guide your next step.' },
];

function MovementPlanPreview() {
  return <div className="relative mx-auto w-full max-w-[500px] animate-rise-in-delay-1">
    <div className="absolute -inset-8 rounded-[3rem] bg-[#d9eee8]/70 blur-3xl" />
    <div className="relative overflow-hidden rounded-[2rem] border border-[hsl(var(--card-border))] bg-[hsl(var(--card))] p-5 shadow-[0_30px_80px_-35px_hsl(var(--foreground)/.35)] md:p-7">
      <div className="flex items-center justify-between border-b border-[hsl(var(--border))] pb-5">
        <div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[hsl(var(--primary))] text-white"><Stethoscope className="h-5 w-5" /></span><div><p className="text-sm font-bold">Today's movement plan</p><p className="mt-1 text-[11px] text-[hsl(var(--muted-foreground))]">Maya Chen · supported squat</p></div></div>
        <span className="flex items-center gap-1.5 text-[10px] font-bold text-[#236b57]"><span className="h-2 w-2 rounded-full bg-[#3e9278]" />Ready</span>
      </div>
      <div className="mt-6 rounded-2xl bg-[hsl(var(--secondary))] p-5 md:p-6"><div className="flex items-end justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[hsl(var(--primary))]">Movement target</p><p className="mt-3 font-display text-6xl leading-none">72°</p></div><div className="text-right"><p className="font-mono-ui text-xs font-bold text-[hsl(var(--primary))]">58° — 78°</p><p className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">comfortable range</p></div></div><div className="mt-7 h-2 rounded-full bg-[hsl(var(--border))]"><div className="relative ml-[58%] h-full w-[20%] rounded-full bg-[hsl(var(--accent))]"><span className="absolute -right-1.5 -top-1.5 h-5 w-5 rounded-full border-2 border-[hsl(var(--primary))] bg-[hsl(var(--card))]" /></div></div></div>
      <div className="mt-5 flex items-center gap-3 rounded-xl border border-[#b9dfd6] bg-[#eef8f4] p-3"><Check className="h-4 w-4 shrink-0 text-[#236b57]" /><p className="text-xs text-[#236b57]">Your therapist's cues are ready when you are.</p></div>
      <div className="mt-5 flex justify-between text-[10px] text-[hsl(var(--muted-foreground))]"><span>3 sets</span><span>8 repetitions</span><span>Approx. 6 min</span></div>
    </div>
  </div>;
}

export function LandingPage() {
  return <div className="min-h-[100dvh] overflow-hidden bg-[hsl(var(--background))] text-[hsl(var(--foreground))]">
    <header className="sticky top-0 z-20 border-b border-[hsl(var(--border))]/70 bg-[hsl(var(--background))]/90 backdrop-blur-md"><div className="mx-auto flex h-[72px] max-w-6xl items-center justify-between px-5 md:px-8"><Link href="/" className="flex items-center gap-3" data-testid="link-home-brand"><BrandMark /><span className="font-semibold tracking-[-0.02em]">kinetic<span className="text-[hsl(var(--primary))]">/</span>care</span></Link><nav className="flex items-center gap-4 md:gap-7"><Link href="/signin" className="text-xs font-semibold text-[hsl(var(--primary))] hover:underline" data-testid="link-signin">Sign in</Link><Link href="/signup" className="inline-flex h-10 items-center rounded-xl bg-[hsl(var(--primary))] px-4 text-xs font-bold text-white shadow-sm transition-transform hover:-translate-y-0.5 md:px-5" data-testid="link-signup">Get started</Link></nav></div></header>
    <main>
      <section className="mx-auto grid max-w-6xl items-center gap-14 px-5 pb-24 pt-16 md:px-8 md:pb-32 md:pt-24 lg:grid-cols-[1fr_.9fr] lg:gap-16"><div className="animate-rise-in"><p className="mb-6 inline-flex items-center gap-2 rounded-full bg-[hsl(var(--secondary))] px-3 py-2 text-[11px] font-bold uppercase tracking-[0.12em] text-[hsl(var(--primary))]"><Activity className="h-3.5 w-3.5" />Movement, made more understandable</p><h1 className="max-w-2xl font-display text-6xl leading-[.88] tracking-[-0.045em] md:text-8xl">A steadier way to <em className="text-[hsl(var(--primary))]">move forward.</em></h1><p className="mt-7 max-w-lg text-base leading-7 text-[hsl(var(--muted-foreground))]">Kinetic Care brings your physiotherapist's plan into everyday practice, with thoughtful technology that helps each movement feel clear, measured, and yours.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/signup" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-6 text-sm font-bold text-white shadow-sm transition-transform hover:-translate-y-0.5" data-testid="link-hero-signup">Get started <ArrowRight className="h-4 w-4" /></Link><Link href="/signin" className="inline-flex h-12 items-center justify-center rounded-xl border border-[hsl(var(--border))] bg-[hsl(var(--card))] px-6 text-sm font-bold text-[hsl(var(--primary))] transition-colors hover:bg-[hsl(var(--secondary))]" data-testid="link-hero-signin">Sign in</Link></div><div className="mt-9 flex items-center gap-3 text-xs text-[hsl(var(--muted-foreground))]"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#b9dfd6] text-[10px] font-bold text-[#175b54]">JM</span><span>Guided by clinicians. Built around people.</span></div></div><MovementPlanPreview /></section>
      <section className="border-y border-[hsl(var(--border))] bg-[hsl(var(--card))]"><div className="mx-auto max-w-6xl px-5 py-20 md:px-8 md:py-24"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[hsl(var(--primary))]">Care, with context</p><h2 className="mt-3 font-display text-5xl leading-none tracking-[-0.035em] md:text-6xl">Guided by clinicians. Built around people.</h2></div><div className="mt-12 grid gap-4 md:grid-cols-3">{credibility.map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-[hsl(var(--card-border))] bg-[hsl(var(--background))] p-6 shadow-[0_12px_30px_-26px_hsl(var(--foreground)/.4)]"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]"><Icon className="h-5 w-5" /></span><h3 className="mt-8 text-lg font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[hsl(var(--muted-foreground))]">{text}</p></div>)}</div></div></section>
      <section className="mx-auto max-w-6xl px-5 py-20 md:px-8 md:py-28"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[hsl(var(--primary))]">The Kinetic Care difference</p><h2 className="mt-3 max-w-xl font-display text-5xl leading-none tracking-[-0.035em] md:text-6xl">More clarity in every phase of care.</h2></div><p className="max-w-sm text-sm leading-6 text-[hsl(var(--muted-foreground))]">A connected experience for the people prescribing movement and the people practicing it.</p></div><div className="mt-14 grid gap-4 md:grid-cols-3">{features.map(({ icon: Icon, number, title, text }) => <article key={title} className="group rounded-2xl border border-[hsl(var(--card-border))] bg-[hsl(var(--card))] p-6 transition-transform hover:-translate-y-1 md:p-7"><div className="flex items-start justify-between"><span className="flex h-12 w-12 items-center justify-center rounded-xl bg-[hsl(var(--secondary))] text-[hsl(var(--primary))]"><Icon className="h-5 w-5" /></span><span className="font-mono-ui text-xs text-[hsl(var(--muted-foreground))]">{number}</span></div><h3 className="mt-16 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[hsl(var(--muted-foreground))]">{text}</p></article>)}</div></section>
      <section className="bg-[hsl(var(--primary))] text-white"><div className="mx-auto max-w-6xl px-5 py-20 md:px-8 md:py-24"><div className="max-w-2xl"><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[hsl(var(--accent))]">A connected care loop</p><h2 className="mt-3 font-display text-5xl leading-none tracking-[-0.035em] md:text-6xl">How it works</h2></div><div className="mt-14 grid gap-8 md:grid-cols-4">{steps.map(({ number, title, text }) => <div key={number} className="border-t border-white/20 pt-5"><span className="font-mono-ui text-xs text-[hsl(var(--accent))]">{number}</span><h3 className="mt-8 text-base font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-white/65">{text}</p></div>)}</div></div></section>
      <section className="mx-5 my-20 overflow-hidden rounded-[2rem] bg-[#e6f2ed] md:mx-auto md:my-28 md:max-w-6xl"><div className="grid items-center gap-10 px-7 py-12 md:grid-cols-[1fr_auto] md:px-14 md:py-16"><div><p className="text-[11px] font-bold uppercase tracking-[0.18em] text-[hsl(var(--primary))]">Your next step can be small</p><h2 className="mt-3 max-w-xl font-display text-5xl leading-none tracking-[-0.035em] md:text-6xl">Begin your rehabilitation journey.</h2><p className="mt-5 max-w-lg text-sm leading-6 text-[hsl(var(--muted-foreground))]">Start with the care team you trust, then let each steady session add up.</p></div><Link href="/signup" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-[hsl(var(--primary))] px-6 text-sm font-bold text-white shadow-sm transition-transform hover:-translate-y-0.5" data-testid="link-final-signup">Get started <ArrowRight className="h-4 w-4" /></Link></div></section>
    </main>
    <footer className="border-t border-[hsl(var(--border))] px-5 py-8 md:px-8"><div className="mx-auto flex max-w-6xl flex-col gap-3 text-xs text-[hsl(var(--muted-foreground))] sm:flex-row sm:items-center sm:justify-between"><span className="font-semibold text-[hsl(var(--foreground))]">kinetic<span className="text-[hsl(var(--primary))]">/</span>care</span><span>Assistive research prototype · Not a diagnosis or medical replacement.</span></div></footer>
  </div>;
}
